--- 
- hosts: all
  become:
  tasks:
    # This task updates our CentOS based systems
    - name: Update
      yum: 
        update_cache=yes
        name=*
        state=latest
        
      when: 
        ansible_distribution == 'CentOS'
  
    
    - name: Install oVirt Repos
      yum:
        name: "centos-release-ovirt42"
      
    - name: Install oVirt Guest Agent
      yum: 
        name: "ovirt-guest-agent-common"
      
    - name: Enable oVirt Guest Agent
      service:
        name: ovirt-guest-agent
        state: started
        
    - name: Install yum-utils
      yum:
        name: yum-utils
        
    - name: Install bind-utils
      yum:
        name: bind-utils
        
    - name: Install net-tools
      yum:
        name: net-tools
    
    - name: Include another yaml file
      include: ntp.yml
    - name: Include Spacewalk registration
      include: spacewalk_reg.yml
