--- 
- hosts: all
  become:
  tasks:
    # This task updates our CentOS based systems
    - name: Update
      yum: 
        update_cache=yes
        name=*
        state=latest
        
      when: 
        ansible_distribution == 'CentOS'
