--- 
- hosts: all
  become:
  tasks:
    # This task updates our CentOS based systems
    - name: Update
      yum: 
        update_cache=yes
        name=*
        state=latest
        
      when: 
        ansible_distribution == 'CentOS'
  
    
    - name: Install oVirt Repos
       yum:
         name: "centos-release-ovirt42"
       become:
    - name: Install oVirt Guest Agent
       yum: 
         name: "ovirt-guest-agent-common"
       become:
    - name: Enable oVirt Guest Agent
      service:
        name: ovirt-guest-agent
        state: started
