- name: Turn of root logins
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^PermitRootLogin '
    line: 'PermitRootLogin no'

- name: Update sudoers file
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    insertafter: '^# %wheel'
    line: 'test           ALL=(ALL)       NOPASSWD: ALL'
