--- 
- hosts: all
  become:
  tasks:
    # This task updates our CentOS based systems
    - name: Update
      yum: 
        update_cache=yes
        name=*
        state=latest
        
      when: 
        ansible_distribution == 'CentOS'
    
    - name: Set MOTD
      copy: src=../files/motd dest=/etc/motd owner=root mode=644
    
    - name: Install Base utilities
      yum: name={{ item }} state=installed
      with_items:
        - yum-utils
        - bind-utils
        - net-tools
    
    - name: Install oVirt Guest Agent
      include: ovirt-guest-agent.yml
    - name: Include another yaml file
      include: ntp.yml
    - name: Include Spacewalk registration
      include: spacewalk_reg.yml
   
